// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWndK3UOhqJ1n3xAILDiTwhCreXiXPnrs',
    appId: '1:1007620129206:web:1699b24c01c418fb564117',
    messagingSenderId: '1007620129206',
    projectId: 'notex-90ae0',
    authDomain: 'notex-90ae0.firebaseapp.com',
    storageBucket: 'notex-90ae0.firebasestorage.app',
    measurementId: 'G-MW9BSQ1F9Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh5Gr3Zh8FN_uWJ6kSSaIjtNOLAAuklYQ',
    appId: '1:1007620129206:android:4f1458a1a3a370f3564117',
    messagingSenderId: '1007620129206',
    projectId: 'notex-90ae0',
    storageBucket: 'notex-90ae0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1BVH-i9Xx-exSk4lw8qKy1goXbpOoRm4',
    appId: '1:1007620129206:ios:4e1cbc80c5b96a8c564117',
    messagingSenderId: '1007620129206',
    projectId: 'notex-90ae0',
    storageBucket: 'notex-90ae0.firebasestorage.app',
    iosBundleId: 'com.example.chronicle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1BVH-i9Xx-exSk4lw8qKy1goXbpOoRm4',
    appId: '1:1007620129206:ios:4e1cbc80c5b96a8c564117',
    messagingSenderId: '1007620129206',
    projectId: 'notex-90ae0',
    storageBucket: 'notex-90ae0.firebasestorage.app',
    iosBundleId: 'com.example.chronicle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWndK3UOhqJ1n3xAILDiTwhCreXiXPnrs',
    appId: '1:1007620129206:web:20487a0fe0873016564117',
    messagingSenderId: '1007620129206',
    projectId: 'notex-90ae0',
    authDomain: 'notex-90ae0.firebaseapp.com',
    storageBucket: 'notex-90ae0.firebasestorage.app',
    measurementId: 'G-MJ5TD987XN',
  );
}
